### ISSUE TITLE
["acts_as_versioned_plugin.sqlite3.db"] are not files

### ISSUE THREAD

**Issue by mjsommer** [jwhitehorn/acts_as_versioned#2]
Receiving the following message while running bundle:

<code>
Using acts_as_versioned (3.2.1) from https://github.com/jwhitehorn/acts_as_versioned.git (at master) 
acts_as_versioned at /Users/sommerm/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/acts_as_versioned-44dfe632ba8c did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["acts_as_versioned_plugin.sqlite3.db"] are not files
</code>

How can I fix this?

**Comment by jwhitehorn** [comment]
That should simply be a warning, as the gemspec in this repo is not valid. It shouldn't be causing you any problems, as bundler is able to work around it.

Ideally I should update it to remove the reference to that file (it doesn't exist), but I haven't yet.

Is the gem working correctly other than this message?

**Comment by mjsommer** [comment]
Thanks Jason, it is "working correctly other than this message". Although, this type of error is not going to fly with my two teams, or with the production guys.

How can I convince you to remove it?

**Comment by mjsommer** [comment]
So, I think I just sent you a Pull Request ... Please check it out!

Martin

**Comment by jwhitehorn** [comment]
Thank you!

I'm on my phone ATM, but I'll review tonight and get back with you.

I appreciate your help.

**Comment by jwhitehorn** [comment]
Pull request #3 looks great!

Thank you for putting that together. I'm merging it in now.
