### ISSUE TITLE
New rubygems.org link is not working

### ISSUE THREAD

**Issue by mjsommer** [jwhitehorn/acts_as_versioned#7]
Jason, the new rubygems.org link we created, is not working. Here is what I have found:

1) gem 'acts_as_versioned_jw', '~> 3.2.2'

Running "bundle" works, but with "rake db:migrate", I get "undefined method `create_versioned_table' for ..."

2) gem 'acts_as_versioned', :git => 'https://github.com/jwhitehorn/acts_as_versioned.git'

Both "bundle" and "rake db:migrate" work.

Is it a naming issue between the gem and the method, or what would you suggest?

**Comment by mjsommer** [comment]
Thanks, I will test it today!

Martin

## 

Sent from my 4G phone.

http://www.linkedin.com/in/martinsommer

**Comment by mjsommer** [comment]
Hi Jason, I tried gem 'acts_as_versioned_jw', '~> 3.2.3', and ran into another undefined method error:

<code>   undefined method `acts_as_versioned' for #Class:0x007ff391ea0768 </code> 

I also tried changing all the acts_as_versioned method calls to acts_as_versioned_jw, and received:

<code> undefined method `acts_as_versioned_jw' for #Class:0x007f923b073ad0 </code> 

Unfortunately, these too approaches also appear to be broken:

<code>   gem 'acts_as_versioned', :git => 'https://github.com/jwhitehorn/acts_as_versioned.git' </code> 
<code>   gem 'acts_as_versioned_jw', :git => 'https://github.com/jwhitehorn/acts_as_versioned.git' </code> 

... with:
<code>   undefined method `acts_as_versioned' for #Class:0x007fc6818a9b58 </code> 

Need your help getting this straightened out.

Thanks,
Martin

**Comment by jwhitehorn** [comment]
That is odd.

I went to an old project that was using this gem and AR 3.2.14, and upgraded acts_as_versioned by simply replacing:

`gem 'acts_as_versioned', :git => 'https://github.com/jwhitehorn/acts_as_versioned.git'`

with:

`gem 'acts_as_versioned_jw', "3.2.3"`

and running `bundle install`. Running existing tests and rake tasks on the project seem to indicate it's working. No errors like that for sure.

I wonder if this is a Rails 4 compatibility thing, but from previous discussions it sounded like you'd had more success than this prior to renaming the gem.

Can you provide a gist of the absolute smallest amount of code needed to reproduce this? That's greatly help.

**Comment by mjsommer** [comment]
Hi Jason, this is pretty easy to replicate. I setup a new Rails 4 test app:

<code>rails new testapp</code>

Generated some code:

<code>rails g scaffold Person name:string</code>

Edited the Gemfile:

<code>gem 'pg'
gem 'acts_as_versioned_jw', '~> 3.2.2'

bundle
</code>

Added the required acts_as_versioned code:

<code>class Person < ActiveRecord::Base
  acts_as_versioned(:version_column => "row_version")
end
</code>

<code>class AddVersioningToLiveData < ActiveRecord::Migration
  def change
    Person.create_versioned_table
  end
end
</code>

Then ran ...

<code>rake db:migrate</code>

... and got:

<code>==  AddVersioningToLiveData: migrating ========================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `acts_as_versioned' for #<Class:0x007fb07c0f8988>/Users/sommerm/dev/testapp/app/models/person.rb:2:in`class:Person'
/Users/sommerm/vmware/dev/RailsTest/testapp/app/models/person.rb:1:in `<top (required)>'
/Users/sommerm/vmware/dev/RailsTest/testapp/db/migrate/20140429043119_add_versioning_to_live_data.rb:3:in`change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)</code>

Please let me know.

PS: If you: 1) comment out your gem, 2) run "bundle clean --force" on your current app, 3) uncomment your gem, and 4) run "bundle", you may see the same activity with your current app.

**Comment by hamzakc** [comment]
+1.  I am running into this issue as well

**Comment by jrtowell** [comment]
+1

**Comment by mjsommer** [comment]
Check out my fixed version at: https://github.com/mjsommer/acts_as_versioned

Fixes this issue, plus some.

https://rubygems.org/gems/db_acts_as_versioned

**Comment by jrtowell** [comment]
Beautiful. Thanks.
